### ISSUE TITLE
Contributor App: Error when trying to execute my draft contract

### ISSUE THREAD

**Issue by chadrickm** [Fermat-ORG/iop-android-governance-apps#2]
Received the following error when trying to execute my draft contract: Execution period must be lower than 120960. It alerted me with the error but then still posted the Contract it seems. The draft allowed me to save it in an error state perhaps.

**Comment by Luis-Fernando-Molina** [comment]
@furszy are you going to fix this? is it already fixed?

**Comment by furszy** [comment]
fixed.
